name: Deploy Marguerite Vue.js App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0' # Specify the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Build the Vue.js app
      run: npm run build

    - name: Deploy to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_PATH: ${{ secrets.SERVER_PATH }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -i private_key.pem -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "rm -rf $SERVER_PATH/*"
        scp -i private_key.pem -o StrictHostKeyChecking=no -r dist/* $SERVER_USER@$SERVER_IP:$SERVER_PATH
        trap 'rm -f private_key.pem' EXIT # Ensure the key is deleted even if the script fails

    - name: Send email notification if build and deployment fails
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        FROM_EMAIL_ADDRESS: ${{ secrets.FROM_EMAIL_ADDRESS }}
        TO_EMAIL_ADDRESS: ${{ secrets.TO_EMAIL_ADDRESS }}
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: $SMTP_SERVER
        server_port: 587
        username: $SMTP_USERNAME
        password: $SMTP_PASSWORD
        subject: "🔴 Fail Marguerite Deployment"
        body: "The deployment of the Marguerite app ('main' branch) failed and the site might be down."
        from: $FROM_EMAIL_ADDRESS
        to: $TO_EMAIL_ADDRESS
    
    - name: Send email notification if build and deployment is successfull
      env:
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        FROM_EMAIL_ADDRESS: ${{ secrets.FROM_EMAIL_ADDRESS }}
        TO_EMAIL_ADDRESS: ${{ secrets.TO_EMAIL_ADDRESS }}
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: $SMTP_SERVER
        server_port: 587
        username: $SMTP_USERNAME
        password: $SMTP_PASSWORD
        subject: "🟢 Success Marguerite Deployment "
        body: "The deployment of the Marguerite app ('main' branch) was successful and the site should be live. Double check this by visiting https://www.marguerite.xyz"
        from: $FROM_EMAIL_ADDRESS
        to: $TO_EMAIL_ADDRESS
